### ISSUE TITLE
Design event schedule section

### ISSUE THREAD

**Issue by tenevdev** [ichealthhack/healthhack17#2]

**Comment by mishrabhinav** [comment]
Can we do something like the ichack schedule? The one on ichack.org.

**Comment by mishrabhinav** [comment]
<img width="1439" alt="screenshot 2017-02-26 23 27 48" src="https://cloud.githubusercontent.com/assets/15222342/23352299/3e02c292-fc7b-11e6-872d-75219b054ee6.png">
 

@tenevdev what do you think?

**Comment by tenevdev** [comment]
That's beautiful
