### ISSUE TITLE
Home (HealthHack) anchor click fails at second trip up

### ISSUE THREAD

**Issue by tenevdev** [ichealthhack/healthhack17#3]
Reproduce by:
  1. Press "Partners" and wait for smooth scrolling to take you to the bottom
  2. Press "HealthHack" - takes you up immediately (that's fine)
  3. Press "Partners" again
  4. Press "HealthHack" - causes a flicker and stays at the Partners section. Another press takes you back up.

**Comment by mishrabhinav** [comment]
@tenevdev I tried reproducing the bug but I didn't notice anything weird with it. However, I pushed something that might fix it. Please have a look and let me know.

**Comment by tenevdev** [comment]
Yes, it scrolls back up now and that works OK. The issue was on Ubuntu running Google Chrome Version 51.0.2704.106 (64-bit).
